/**
 * Report Model
 *
 * Mongoose schema for report metadata.
 * Stores information about generated reports.
 */
import mongoose from "mongoose";

const reportSchema = new mongoose.Schema(
  {
    organizationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Organization",
      required: [true, "Organization is required"],
      index: true,
    },
    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: [true, "Generated by is required"],
    },
    reportType: {
      type: String,
      enum: [
        "attendance",
        "leave",
        "task",
        "overtime",
        "team",
        "user",
        "dashboard",
        "custom",
      ],
      required: [true, "Report type is required"],
      index: true,
    },
    title: {
      type: String,
      required: [true, "Title is required"],
      trim: true,
      maxlength: 200,
    },
    description: {
      type: String,
      trim: true,
      maxlength: 500,
      default: null,
    },
    filters: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
    startDate: {
      type: Date,
      default: null,
    },
    endDate: {
      type: Date,
      default: null,
    },
    format: {
      type: String,
      enum: ["json", "csv", "pdf"],
      default: "json",
    },
    fileUrl: {
      type: String,
      trim: true,
      default: null,
    },
    status: {
      type: String,
      enum: ["pending", "processing", "completed", "failed"],
      default: "completed",
    },
    data: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },
    expiresAt: {
      type: Date,
      default: function () {
        // Reports expire after 7 days
        return new Date(Date.now() + 7 * 24 * 60 * 60 * 1000);
      },
    },
    isDeleted: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Compound indexes
reportSchema.index({ organizationId: 1, reportType: 1 });
reportSchema.index({ organizationId: 1, generatedBy: 1 });
reportSchema.index({ expiresAt: 1 }, { sparse: true });

/**
 * Virtual: Check if report is expired
 */
reportSchema.virtual("isExpired").get(function () {
  if (!this.expiresAt) return false;
  return new Date() > this.expiresAt;
});

/**
 * Static: Get reports
 */
reportSchema.statics.getReports = async function (organizationId, options = {}) {
  const { page = 1, limit = 20, reportType, generatedBy } = options;

  const query = { organizationId, isDeleted: false };

  if (reportType) query.reportType = reportType;
  if (generatedBy) query.generatedBy = generatedBy;

  const [reports, total] = await Promise.all([
    this.find(query)
      .populate("generatedBy", "firstName lastName")
      .sort({ createdAt: -1 })
      .skip((page - 1) * limit)
      .limit(limit)
      .lean(),
    this.countDocuments(query),
  ]);

  return {
    reports,
    pagination: {
      page,
      limit,
      total,
      pages: Math.ceil(total / limit),
    },
  };
};

/**
 * Pre-save hook: Auto-delete expired reports
 */
reportSchema.pre("save", function (next) {
  if (this.expiresAt && new Date() > this.expiresAt) {
    this.isDeleted = true;
  }
  next();
});

const Report = mongoose.model("Report", reportSchema);

export default Report;
